spring:
  application:
    name: zuul-server
  redis:
    host: 192.168.140.129
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 4
    cluster:
      nodes: 192.168.140.129:7001,192.168.140.129:7002,192.168.140.129:7003
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 编写zuul的路由表
zuul:
  routes:
    api-worker-ribbon:
      path: /ribbon/**
      serviceId: WORKER-CONSUMER
    api-worker-feign:
      path: /feign/**
      serviceId: WORKER-CONSUMER-FEIGN
  # 统一前缀的配置
  prefix: /api
  # 保护敏感路径：所有只要包含/admin/路径的访问都会被拒绝，在业务场景中 admin 的访问应该属于内部管理员访问的路径
  ignored-patterns: /**/admin/**
  # 敏感头：设置敏感头集合为空的,这样就可以携带cookie了
  sensitive-headers:
# ribbon的超时配置
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
