spring:
  application:
    name: worker-provider
  #数据库信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_data_view?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true
    username: root
    password: 7901
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8788
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:META-INF/mapper/*.xml


